# Generated by Django 3.1.7 on 2021-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebsite', '0003_remove_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
