# Generated by Django 3.1.7 on 2021-04-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebsite', '0004_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timeZone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamewebsite.timezones'),
        ),
    ]
