# Generated by Django 3.1.7 on 2021-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebsite', '0005_auto_20210401_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequests',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
